version: "2"
services:
  api:
    image: revenuewire/validator:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - $PWD:/var/src

  unittest:
    image: revenuewire/validator:latest
    volumes:
        - $PWD:/var/src
    working_dir: /var/src/
    command: ./bin/run-test.sh